AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sam for frontend
Resources:
    WebsiteBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: ai-photo-album2.com
            PublicAccessBlockConfiguration:
                BlockPublicAcls: FALSE
                BlockPublicPolicy: FALSE
                IgnorePublicAcls: FALSE
                RestrictPublicBuckets: FALSE
            WebsiteConfiguration:
                IndexDocument: pa-2-index.html
    WebsiteBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref WebsiteBucket
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    -   Action:
                            - '*'
                        Effect: Allow
                        Resource: !Sub
                            -   arn:aws:s3:::${PhotoBucket}/*
                            -   { PhotoBucket: !Ref WebsiteBucket }
                        Principal: '*'
                        Sid: PublicReadGetObject
    WebsiteCloudFront:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Comment: CloudFront for Photo Album
                CacheBehaviors:
                    -   AllowedMethods:
                            -   GET
                            -   HEAD
                        CachedMethods:
                            -   GET
                            -   HEAD
                        Compress: FALSE
                        DefaultTTL: 86400
                        ForwardedValues:
                            QueryString: FALSE
                        MaxTTL: 31536000
                        MinTTL: 0
                        PathPattern: '*'
                        SmoothStreaming: FALSE
                        TargetOriginId: S3-ai-photo-album2.com
                        ViewerProtocolPolicy: redirect-to-https
                DefaultRootObject: pa-2-index.html
                Enabled: TRUE
                HttpVersion: http2
                IPV6Enabled: TRUE
                Origins:
                    -   DomainName: ai-photo-album.com.s3.amazonaws.com
                        Id: S3-ai-photo-album.com
                        CustomOriginConfig:
                            OriginProtocolPolicy: http-only
                ViewerCertificate:
                    CloudFrontDefaultCertificate: TRUE